packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@google/genai': false
  '@parcel/watcher': true
  electron-winstaller: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
patchedDependencies:
  vite-plugin-babel@1.7.3: patches/vite-plugin-babel@1.7.3.patch
