/** Localized copy shared by browser and Electron Renderer hosts. */
export type AgentLocale = 'en' | 'zh-CN'

/** 设置弹窗「界面」分组中的语言选项；名称使用各语言的自称，不随界面语言变化。 */
export const AGENT_LOCALE_OPTIONS: ReadonlyArray<{ value: AgentLocale; label: string }> = [
  { value: 'en', label: 'English' },
  { value: 'zh-CN', label: '简体中文' },
]

const copy = {
  en: {
    agent: 'Agent Alpha',
    timeline: 'Agent timeline',
    newSession: 'New session',
    renameSession: 'Rename session',
    deleteSession: 'Delete session',
    settings: 'Model settings',
    closePanel: 'Close Agent panel',
    interface: 'Interface',
    language: 'Language',
    connected: 'Connected',
    testing: 'Testing',
    notConfigured: 'Setup required',
    connectionError: 'Connection error',
    noModel: 'No model selected',
    emptyTitle: 'What should we inspect?',
    emptyBody: 'Ask about the visible chart or make a bounded chart change.',
    promptTrend: 'Summarize the current trend and key levels',
    promptRsi: 'Analyze RSI(14) over the latest 20 bars',
    promptEma: 'Add EMA(20) to the main chart',
    promptTheme: 'Switch the chart to dark theme',
    readOnly: 'Read-only',
    readOnlyHint: 'Block chart changes',
    noSymbol: 'No symbol',
    noPeriod: 'No period',
    noRange: 'No range',
    injectedKLineBars: 'Injection preview',
    injectedKLineBarsDescription: 'Preview of the ContextItem data supplied to the model.',
    showInjectedKLineBars: 'Show preview',
    hideInjectedKLineBars: 'Hide preview',
    injectedKLineBarsCount: 'ContextItems injected',
    composerPlaceholder: 'Ask about this chart...',
    send: 'Send',
    stop: 'Stop',
    steeringDisabled: 'A run is active. Your draft will stay here.',
    action: 'Action',
    reasoning: 'Reasoning',
    reasoningEffort: 'Reasoning effort',
    collapseReasoning: 'Collapse reasoning',
    input: 'Input',
    output: 'Output',
    total: 'Total',
    result: 'Result',
    evidence: 'Evidence',
    locate: 'Locate on chart',
    undo: 'Undo',
    retry: 'Retry',
    confirm: 'Confirm',
    cancel: 'Cancel',
    reject: 'Reject',
    reversible: 'Reversible',
    irreversible: 'Not reversible',
    required: 'Confirmation required',
    recommended: 'Recommended action',
    question: {
      required: 'Clarification required',
      submit: 'Send answer',
      freeText: 'Or type your own requirement',
      answered: 'Answered',
      cancelled: 'Question cancelled',
    },
    tokens: 'tokens',
    providerTitle: 'Model provider',
    providerSettings: 'Provider settings',
    externalServices: 'External services',
    tools: 'Tools',
    noTools: 'No Agent tools are registered.',
    toolParameters: 'Parameters (JSON)',
    toolRun: 'Run',
    toolRunning: 'Running...',
    providerBody: 'Connect your OpenAI-compatible endpoint for Agent runs.',
    providerProfile: 'Configuration',
    providerProfileName: 'Configuration name',
    providerProfileNameDuplicated: 'A configuration with this name already exists.',
    newProviderProfile: 'New configuration',
    renameProviderProfile: 'Rename configuration',
    deleteProviderProfile: 'Delete configuration',
    deleteProviderProfileConfirm: 'Delete this configuration? Its model pool is removed too.',
    addModel: 'Add model',
    apiProtocol: 'API protocol',
    openAiCompletions: 'Open AI Completions',
    openAiResponses: 'Open AI Response',
    baseUrl: 'Base URL',
    apiKey: 'API key',
    exaApiKey: 'Exa API key',
    exaApiKeyPlaceholder: 'Leave blank to keep the saved key',
    additionalHeaders: 'Additional headers (JSON)',
    additionalHeadersPlaceholder:
      '{\n  "HTTP-Referer": "https://example.com",\n  "X-OpenRouter-Title": "My app"\n}',
    model: 'Model ID',
    modelList: 'Available models',
    modelPool: 'Model pool',
    contextWindow: 'Context',
    noModelsInPool: 'Add at least one model to the model pool.',
    loadingModels: 'Loading models...',
    testConnection: 'Test connection',
    refreshModels: 'Refresh model list',
    modelSearchPlaceholder: 'Search',
    probeResults: 'Compatibility test results',
    probeCatalog: 'Catalog and authentication',
    probeText: 'Minimal text response',
    probeTool: 'Harmless tool call',
    apiKeyPlaceholder: 'Leave blank to use the saved credential',
    modelPlaceholder: 'Select a model',
    providerDraftNotice: 'Your current draft will be preserved.',
    sessionNamePrompt: 'Session name',
    deleteSessionConfirm: 'Delete this session?',
    status: {
      idle: 'Ready',
      running: 'Running',
      cancelling: 'Stopping',
      completed: 'Completed',
      failed: 'Failed',
      cancelled: 'Cancelled',
      partial: 'Partially completed',
      interrupted: 'Interrupted',
      queued: 'Queued',
      'requires-confirmation': 'Waiting for confirmation',
      succeeded: 'Succeeded',
      confirmed: 'Confirmed',
      rejected: 'Rejected',
      expired: 'Expired',
      undone: 'Undone',
    },
  },
  'zh-CN': {
    agent: 'Agent Alpha',
    timeline: 'Agent 时间线',
    newSession: '新建会话',
    renameSession: '重命名会话',
    deleteSession: '删除会话',
    settings: '模型设置',
    closePanel: '关闭 Agent 面板',
    interface: '界面',
    language: '语言',
    connected: '已连接',
    testing: '测试中',
    notConfigured: '需要设置',
    connectionError: '连接错误',
    noModel: '未选择模型',
    emptyTitle: '想检查什么？',
    emptyBody: '可以询问当前可见图表，或执行边界明确的图表操作。',
    promptTrend: '总结当前趋势和关键价位',
    promptRsi: '分析最近 20 根 K 线的 RSI(14)',
    promptEma: '在主图添加 EMA(20)',
    promptTheme: '切换图表为深色主题',
    readOnly: '只读',
    readOnlyHint: '禁止修改图表',
    noSymbol: '无标的',
    noPeriod: '无周期',
    noRange: '无区间',
    injectedKLineBars: '注入预览',
    injectedKLineBarsDescription: '模型实际接收的 ContextItem 数据预览。',
    showInjectedKLineBars: '查看预览',
    hideInjectedKLineBars: '收起预览',
    injectedKLineBarsCount: '个 ContextItem 已注入',
    composerPlaceholder: '询问当前图表...',
    send: '发送',
    stop: '停止',
    steeringDisabled: '任务正在运行，当前草稿会保留。',
    action: '操作',
    reasoning: '思考',
    reasoningEffort: '推理强度',
    collapseReasoning: '折叠思考过程',
    input: '输入',
    output: '输出',
    total: '共计',
    result: '结果',
    evidence: '证据',
    locate: '在图表中定位',
    undo: '撤销',
    retry: '重试',
    confirm: '确认',
    cancel: '取消',
    reject: '拒绝',
    reversible: '可撤销',
    irreversible: '不可撤销',
    required: '需要确认',
    recommended: '建议操作',
    question: {
      required: '需要澄清',
      submit: '提交回答',
      freeText: '或直接输入你的要求',
      answered: '已回答',
      cancelled: '提问已取消',
    },
    tokens: 'tokens',
    providerTitle: '模型 Provider',
    providerSettings: '供应商设置',
    externalServices: '外部服务',
    tools: '工具',
    noTools: '当前没有已注册的 Agent 工具。',
    toolParameters: '参数（JSON）',
    toolRun: '运行',
    toolRunning: '运行中...',
    providerBody: '连接你自己的 OpenAI-compatible 端点以运行 Agent。',
    providerProfile: '配置',
    providerProfileName: '配置名称',
    providerProfileNameDuplicated: '已存在同名配置。',
    newProviderProfile: '新建配置',
    renameProviderProfile: '重命名配置',
    deleteProviderProfile: '删除配置',
    deleteProviderProfileConfirm: '删除这个配置？其模型池也会一并移除。',
    addModel: '添加模型',
    apiProtocol: 'API 协议',
    openAiCompletions: 'Open AI Completions',
    openAiResponses: 'Open AI Response',
    baseUrl: 'Base URL',
    apiKey: 'API key',
    exaApiKey: 'Exa API key',
    exaApiKeyPlaceholder: '留空则保留已保存的 Key',
    additionalHeaders: '附加请求头（JSON）',
    additionalHeadersPlaceholder:
      '{\n  "HTTP-Referer": "https://example.com",\n  "X-OpenRouter-Title": "我的应用"\n}',
    model: '模型 ID',
    modelList: '可用模型',
    modelPool: '模型池',
    contextWindow: '上下文',
    noModelsInPool: '请至少向模型池添加一个模型。',
    loadingModels: '正在加载模型...',
    testConnection: '测试连接',
    refreshModels: '刷新模型列表',
    modelSearchPlaceholder: '搜索',
    probeResults: '兼容性测试结果',
    probeCatalog: '模型目录与鉴权',
    probeText: '最小文本回复',
    probeTool: '无副作用工具调用',
    apiKeyPlaceholder: '留空则使用已保存的凭据',
    modelPlaceholder: '选择模型',
    providerDraftNotice: '当前草稿会保留。',
    sessionNamePrompt: '会话名称',
    deleteSessionConfirm: '删除这个会话？',
    status: {
      idle: '就绪',
      running: '运行中',
      cancelling: '正在停止',
      completed: '已完成',
      failed: '失败',
      cancelled: '已取消',
      partial: '部分完成',
      interrupted: '已中断',
      queued: '排队中',
      'requires-confirmation': '等待确认',
      succeeded: '成功',
      confirmed: '已确认',
      rejected: '已拒绝',
      expired: '已过期',
      undone: '已撤销',
    },
  },
} as const

export function getAgentCopy(locale: AgentLocale) {
  return copy[locale]
}
